//! Shared protocol types for poe frontends and core.

use std::path::PathBuf;

use serde::{Deserialize, Serialize};

/// Operations submitted by a frontend to the core session.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Op {
    /// Starts one user turn in the requested working directory.
    UserTurn { prompt: String, cwd: PathBuf },
    /// Requests cancellation of the current turn when supported.
    Interrupt,
    /// Requests conversation compaction when supported.
    Compact,
    /// Requests an orderly session shutdown.
    Shutdown,
}

/// Events emitted by the core session for frontends to render or serialize.
// `Usage` carries an `f64` cost, so this enum is `PartialEq` but not `Eq`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Event {
    /// The session has started and can accept turn activity.
    SessionStarted,
    /// A streamed chunk of assistant-visible text.
    AssistantDelta { text: String },
    /// A streamed chunk of model reasoning/thinking text.
    ThinkingDelta { text: String },
    /// A tool call has started.
    ToolStarted { call: ToolCall },
    /// A streamed chunk of tool output.
    ToolOutput {
        id: String,
        stream: ToolOutputStream,
        chunk: String,
    },
    /// A tool call has finished and produced a model-visible summary.
    ToolFinished { id: String, result: ToolResult },
    /// A patch has been proposed before application.
    PatchProposed {
        id: String,
        changes: Vec<FileChange>,
    },
    /// A patch has been applied successfully.
    PatchApplied {
        id: String,
        changes: Vec<FileChange>,
    },
    /// A patch failed before or during application.
    PatchFailed { id: String, message: String },
    /// The current turn completed successfully.
    TurnComplete,
    /// The current turn was interrupted before completion at the user's request.
    TurnInterrupted,
    /// The current turn failed with a user-visible message.
    TurnFailed { message: String },
    /// A model request failed and is being retried. `retry` is the 1-based
    /// number of this retry (the original request is not a retry) out of
    /// `max_retries` possible retries.
    Retrying { retry: usize, max_retries: usize },
    /// Token and cost accounting for one completed model request. The agent
    /// loop emits one of these per request (i.e. per tool round), so frontends
    /// accumulate them for session totals.
    Usage { usage: TokenUsage },
}

/// Token and cost accounting reported by the model provider for a single
/// request. Token counts are cumulative-safe via saturating addition; `cost`
/// is in USD (OpenRouter credits, where 1 credit = $1).
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize)]
pub struct TokenUsage {
    /// Total input/prompt tokens, including any served from cache.
    pub input_tokens: u64,
    /// Input tokens served from the prompt cache (a subset of `input_tokens`).
    /// These are cache *reads*.
    pub cached_tokens: u64,
    /// Input tokens written to the prompt cache (cache *writes*). Distinct from
    /// `cached_tokens`: writes happen the first time a prefix is seen, reads on
    /// later requests that reuse it.
    pub cache_write_tokens: u64,
    /// Output/completion tokens generated by the model.
    pub output_tokens: u64,
    /// Request cost in USD.
    pub cost_usd: f64,
}

impl TokenUsage {
    /// Adds another usage report into this running total.
    pub fn add(&mut self, other: &TokenUsage) {
        self.input_tokens = self.input_tokens.saturating_add(other.input_tokens);
        self.cached_tokens = self.cached_tokens.saturating_add(other.cached_tokens);
        self.cache_write_tokens = self
            .cache_write_tokens
            .saturating_add(other.cache_write_tokens);
        self.output_tokens = self.output_tokens.saturating_add(other.output_tokens);
        self.cost_usd += other.cost_usd;
    }
}

/// A model-requested tool invocation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolCall {
    /// Stable identifier used to associate outputs and results with this call.
    pub id: String,
    /// Tool name as understood by the core tool router.
    pub name: String,
    /// Structured tool input; concrete schemas live with each tool.
    pub input: serde_json::Value,
}

/// One message in a persisted conversation transcript, mirroring the chat
/// roles exchanged with the model: system prompt, user turns, assistant
/// replies (text and/or tool calls), and tool results.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "role", rename_all = "snake_case")]
pub enum TranscriptMessage {
    System {
        content: String,
    },
    User {
        content: String,
    },
    Assistant {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        reasoning_content: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        content: Option<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        tool_calls: Vec<ToolCall>,
    },
    Tool {
        tool_call_id: String,
        content: String,
    },
}

/// The output stream a tool chunk came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ToolOutputStream {
    Stdout,
    Stderr,
}

/// Final model-visible result of a tool call.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ToolResult {
    /// Process-style exit code when the tool has one.
    pub exit_code: Option<i32>,
    /// Bounded summary returned to the model.
    pub summary: String,
}

/// One file affected by a proposed or applied patch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileChange {
    pub path: PathBuf,
    pub kind: FileChangeKind,
}

/// The kind of file operation represented by a patch change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileChangeKind {
    Add,
    Update,
    Delete,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::{Value, json};

    #[test]
    fn user_turn_uses_expected_wire_tag_and_round_trips() {
        let op = Op::UserTurn {
            prompt: "say hello".to_string(),
            cwd: PathBuf::from("/tmp/project"),
        };

        let value = serde_json::to_value(&op).expect("serialize op");

        assert_eq!(value["type"], "user_turn");
        assert_eq!(
            serde_json::from_value::<Op>(value).expect("deserialize op"),
            op
        );
    }

    #[test]
    fn assistant_delta_uses_expected_wire_tag_and_round_trips() {
        let event = Event::AssistantDelta {
            text: "hello".to_string(),
        };

        assert_event_round_trips_with_type(event, "assistant_delta");
    }

    #[test]
    fn tool_output_preserves_stream_names() {
        assert_event_round_trips_with_value(
            Event::ToolOutput {
                id: "call-1".to_string(),
                stream: ToolOutputStream::Stdout,
                chunk: "ok".to_string(),
            },
            json!({
                "type": "tool_output",
                "id": "call-1",
                "stream": "stdout",
                "chunk": "ok"
            }),
        );

        assert_event_round_trips_with_value(
            Event::ToolOutput {
                id: "call-2".to_string(),
                stream: ToolOutputStream::Stderr,
                chunk: "warning".to_string(),
            },
            json!({
                "type": "tool_output",
                "id": "call-2",
                "stream": "stderr",
                "chunk": "warning"
            }),
        );
    }

    #[test]
    fn patch_proposed_preserves_paths_and_change_kinds() {
        assert_event_round_trips_with_value(
            Event::PatchProposed {
                id: "patch-1".to_string(),
                changes: vec![
                    FileChange {
                        path: PathBuf::from("src/main.rs"),
                        kind: FileChangeKind::Update,
                    },
                    FileChange {
                        path: PathBuf::from("README.md"),
                        kind: FileChangeKind::Add,
                    },
                    FileChange {
                        path: PathBuf::from("old.txt"),
                        kind: FileChangeKind::Delete,
                    },
                ],
            },
            json!({
                "type": "patch_proposed",
                "id": "patch-1",
                "changes": [
                    { "path": "src/main.rs", "kind": "update" },
                    { "path": "README.md", "kind": "add" },
                    { "path": "old.txt", "kind": "delete" }
                ]
            }),
        );
    }

    #[test]
    fn usage_event_round_trips_with_value() {
        assert_event_round_trips_with_value(
            Event::Usage {
                usage: TokenUsage {
                    input_tokens: 194,
                    cached_tokens: 100,
                    cache_write_tokens: 50,
                    output_tokens: 2,
                    cost_usd: 0.95,
                },
            },
            json!({
                "type": "usage",
                "usage": {
                    "input_tokens": 194,
                    "cached_tokens": 100,
                    "cache_write_tokens": 50,
                    "output_tokens": 2,
                    "cost_usd": 0.95
                }
            }),
        );
    }

    #[test]
    fn token_usage_accumulates_with_saturating_token_addition() {
        let mut total = TokenUsage::default();
        total.add(&TokenUsage {
            input_tokens: 100,
            cached_tokens: 40,
            cache_write_tokens: 60,
            output_tokens: 10,
            cost_usd: 0.01,
        });
        total.add(&TokenUsage {
            input_tokens: 200,
            cached_tokens: 150,
            cache_write_tokens: 0,
            output_tokens: 20,
            cost_usd: 0.02,
        });

        assert_eq!(total.input_tokens, 300);
        assert_eq!(total.cached_tokens, 190);
        assert_eq!(total.cache_write_tokens, 60);
        assert_eq!(total.output_tokens, 30);
        assert!((total.cost_usd - 0.03).abs() < 1e-9);
    }

    #[test]
    fn turn_failed_preserves_message() {
        assert_event_round_trips_with_value(
            Event::TurnFailed {
                message: "model request failed".to_string(),
            },
            json!({
                "type": "turn_failed",
                "message": "model request failed"
            }),
        );
    }

    #[test]
    fn tool_started_preserves_structured_input() {
        assert_event_round_trips_with_value(
            Event::ToolStarted {
                call: ToolCall {
                    id: "call-1".to_string(),
                    name: "shell".to_string(),
                    input: json!({ "argv": ["cargo", "test"] }),
                },
            },
            json!({
                "type": "tool_started",
                "call": {
                    "id": "call-1",
                    "name": "shell",
                    "input": { "argv": ["cargo", "test"] }
                }
            }),
        );
    }

    fn assert_event_round_trips_with_type(event: Event, event_type: &str) {
        let value = serde_json::to_value(&event).expect("serialize event");

        assert_eq!(value["type"], event_type);
        assert_eq!(
            serde_json::from_value::<Event>(value).expect("deserialize event"),
            event
        );
    }

    fn assert_event_round_trips_with_value(event: Event, expected: Value) {
        let value = serde_json::to_value(&event).expect("serialize event");

        assert_eq!(value, expected);
        assert_eq!(
            serde_json::from_value::<Event>(value).expect("deserialize event"),
            event
        );
    }

    #[test]
    fn transcript_messages_use_role_tag_and_round_trip() {
        let messages = vec![
            TranscriptMessage::System {
                content: "You are a coding agent.".to_string(),
            },
            TranscriptMessage::User {
                content: "say hello".to_string(),
            },
            TranscriptMessage::Assistant {
                reasoning_content: Some("thinking it through".to_string()),
                content: Some("on it".to_string()),
                tool_calls: vec![ToolCall {
                    id: "call-1".to_string(),
                    name: "read_file".to_string(),
                    input: json!({ "file_path": "/tmp/a" }),
                }],
            },
            TranscriptMessage::Tool {
                tool_call_id: "call-1".to_string(),
                content: "file contents".to_string(),
            },
        ];

        let value = serde_json::to_value(&messages).expect("serialize transcript");

        assert_eq!(value[0]["role"], "system");
        assert_eq!(value[2]["role"], "assistant");
        assert_eq!(value[2]["reasoning_content"], "thinking it through");
        assert_eq!(value[2]["tool_calls"][0]["name"], "read_file");
        assert_eq!(value[3]["role"], "tool");
        assert_eq!(
            serde_json::from_value::<Vec<TranscriptMessage>>(value)
                .expect("deserialize transcript"),
            messages
        );
    }

    #[test]
    fn assistant_message_omits_empty_optional_fields() {
        let value = serde_json::to_value(TranscriptMessage::Assistant {
            reasoning_content: None,
            content: None,
            tool_calls: Vec::new(),
        })
        .expect("serialize assistant");

        assert_eq!(value, json!({ "role": "assistant" }));
    }
}
